language: rust
rust:
- stable
- beta
- nightly
sudo: false
os:
- linux
cache:
  directories:
  - $HOME/.cargo
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - CARGO_FEATURES=
  global:
  - CARGO_QUIET=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src

script:
- cargo test
- cargo build

deploy:
  provider: script
  script: "true"
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"

before_deploy:
- cargo doc
- cargo package

after_deploy:
- cargo pages-publish
- cargo publish
